### ISSUE TITLE
This.context.map undefined

### ISSUE THREAD

**Issue by seshu3564** [lycheelin/react-leaflet-canvas-markers#1]
When I am trying to use your library by copying both files. I am getting error from your CanvasMarkersLayer.js file because my context was empty when i tried printing this.context before the below in componentWillMount function
```this.leafletElement.addTo(this.context.map);``` 
Where as when i ran your example and kept print i could get this.context value with map key.
Can you please tell me how you got this.context here so that i know where i made mistake in my project

**Comment by sfivash** [comment]
I have the same problem.  It looks like the issue is because react-leaflet changed how it accesses the [context in the update to V2](https://react-leaflet.js.org/docs/en/context.html) and this plugin is not compatible with V2.  The example in here is using v1.9.1 

You could try downgrading your react-leaflet to v1.9.1.  

That didn't work for me though, I got another error "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object." but I'm using bit of a different setup than the example.  I'm using Gatsby.

**Comment by seshu3564** [comment]
Thanks for the suggestion it worked fine once i downgraded the react-leaflet to v1.9.1

**Comment by lycheelin** [comment]
It can work with react-leaflet V2.x now
